VENUES = {
    "elsewhere-brooklyn": {
        "name": "Elsewhere Brooklyn",
        "capacity": 800,
        "venue_type": "music venue and bar",
        "address": "599 Johnson Ave, Brooklyn, NY 11237",
        "current_carrier": "Admitted Market A",
        "renewal_date": "2026-10-15",
        # Scoring attributes
        "incident_count": 2,
        "compliance_items": 0,
        "security_level": "high",
        "years_in_operation": 12,
        "prior_carrier": "Admitted Market A",
        # Live infrastructure
        "infrastructure": [
            {"name": "DOOR_ID_SCANNER [FRONT]", "status": "ACTIVE", "detail": "[742/HR]", "is_degraded": False},
            {"name": "GUESTLIST_SYNC [DICE.FM]", "status": "ACTIVE", "detail": "[REALTIME]", "is_degraded": False},
            {"name": "CAMERA_FEED_REAR", "status": "DEGRADED", "detail": "[12% LOSS]", "is_degraded": True},
        ],
    },
    "brooklyn-mirage": {
        "name": "Brooklyn Mirage",
        "capacity": 5000,
        "venue_type": "outdoor music venue",
        "address": "140 Stewart Ave, Brooklyn, NY 11237",
        "current_carrier": "Surplus Lines B",
        "renewal_date": "2026-08-01",
        "incident_count": 5,
        "compliance_items": 1,
        "security_level": "high",
        "years_in_operation": 6,
        "prior_carrier": "Surplus Lines B",
        "infrastructure": [
            {"name": "PERIMETER_SCANNER [MAIN]", "status": "ACTIVE", "detail": "[4650/HR]", "is_degraded": False},
            {"name": "GUESTLIST_SYNC [SEE TICKETS]", "status": "ACTIVE", "detail": "[REALTIME]", "is_degraded": False},
            {"name": "CAMERA_STAGE_LEFT", "status": "ACTIVE", "detail": "[ONLINE]", "is_degraded": False},
            {"name": "POS_BAR_EAST", "status": "ACTIVE", "detail": "[REALTIME]", "is_degraded": False},
        ],
    },
    "house-of-yes": {
        "name": "House of Yes",
        "capacity": 600,
        "venue_type": "nightclub and performance space",
        "address": "2 Wyckoff Ave, Brooklyn, NY 11237",
        "current_carrier": "Admitted Market A",
        "renewal_date": "2026-12-01",
        "incident_count": 7,
        "compliance_items": 0,
        "security_level": "medium",
        "years_in_operation": 9,
        "prior_carrier": "Admitted Market A",
        "infrastructure": [
            {"name": "DOOR_ID_SCANNER [ENTRY]", "status": "ACTIVE", "detail": "[558/HR]", "is_degraded": False},
            {"name": "CAMERA_MAIN_FLOOR", "status": "ACTIVE", "detail": "[ONLINE]", "is_degraded": False},
            {"name": "POS_BAR_PRIMARY", "status": "DEGRADED", "detail": "[OFFLINE]", "is_degraded": True},
        ],
    },
    "nowadays": {
        "name": "Nowadays",
        "capacity": 400,
        "venue_type": "outdoor bar and music venue",
        "address": "56-06 Cooper Ave, Ridgewood, NY 11385",
        "current_carrier": "Surplus Lines C",
        "renewal_date": "2027-03-01",
        "incident_count": 1,
        "compliance_items": 2,
        "security_level": "medium",
        "years_in_operation": 4,
        "prior_carrier": "Surplus Lines C",
        "infrastructure": [
            {"name": "DOOR_ID_SCANNER [OUTDOOR]", "status": "ACTIVE", "detail": "[372/HR]", "is_degraded": False},
            {"name": "POS_BAR_OUTDOOR", "status": "ACTIVE", "detail": "[REALTIME]", "is_degraded": False},
        ],
    },
    "market-hotel": {
        "name": "Market Hotel",
        "capacity": 350,
        "venue_type": "DIY music venue and bar",
        "address": "1140 Myrtle Ave, Brooklyn, NY 11221",
        "current_carrier": "Admitted Market B",
        "renewal_date": "2026-11-01",
        "incident_count": 3,
        "compliance_items": 3,
        "security_level": "low",
        "years_in_operation": 16,
        "prior_carrier": "Admitted Market B",
        "infrastructure": [
            {"name": "DOOR_ID_SCANNER [MAIN]", "status": "ACTIVE", "detail": "[310/HR]", "is_degraded": False},
            {"name": "CAMERA_ENTRANCE", "status": "DEGRADED", "detail": "[NO SIGNAL]", "is_degraded": True},
            {"name": "CAMERA_STAGE", "status": "DEGRADED", "detail": "[OFFLINE]", "is_degraded": True},
        ],
    },
}


SEED_INCIDENTS = [
    # Elsewhere Brooklyn
    {
        "venue_id": "elsewhere-brooklyn",
        "occurred_at": "2026-05-02T23:13:00",
        "location": "Rear Bar",
        "summary": "Two patrons began fighting near the rear bar during a sold-out DJ event. One patron sustained a cut to the face.",
        "reported_by": "Shift Lead",
        "injury_observed": True,
        "police_called": True,
        "ems_called": False,
    },
    {
        "venue_id": "elsewhere-brooklyn",
        "occurred_at": "2026-04-18T01:45:00",
        "location": "Main Stairwell",
        "summary": "Patron slipped on wet stairs near the main stairwell and fell. Complained of knee pain. No EMS called.",
        "reported_by": "Floor Manager",
        "injury_observed": True,
        "police_called": False,
        "ems_called": False,
    },
    # Brooklyn Mirage
    {
        "venue_id": "brooklyn-mirage",
        "occurred_at": "2026-04-25T22:30:00",
        "location": "Main Stage Pit",
        "summary": "Crowd surge near the main stage during headliner set. Three patrons reported feeling faint. EMS called as precaution.",
        "reported_by": "Head of Security",
        "injury_observed": True,
        "police_called": False,
        "ems_called": True,
    },
    {
        "venue_id": "brooklyn-mirage",
        "occurred_at": "2026-04-10T04:07:00",
        "location": "East Bar",
        "summary": "POS logs show spirits sold at 4:07 AM, past the 4:00 AM legal service cutoff. Bartender was unaware of last call policy.",
        "reported_by": "Operations Manager",
        "injury_observed": False,
        "police_called": False,
        "ems_called": False,
    },
    # House of Yes
    {
        "venue_id": "house-of-yes",
        "occurred_at": "2026-05-01T00:15:00",
        "location": "Dance Floor",
        "summary": "Patron alleged assault by another guest on the dance floor. Victim requested police. Alleged attacker escorted out before arrival.",
        "reported_by": "Security Lead",
        "injury_observed": True,
        "police_called": True,
        "ems_called": False,
    },
    {
        "venue_id": "house-of-yes",
        "occurred_at": "2026-04-20T02:30:00",
        "location": "Backstage Corridor",
        "summary": "Patron found unresponsive in backstage corridor. EMS called immediately. Patron transported to hospital. Suspected drug overdose.",
        "reported_by": "Venue Manager",
        "injury_observed": True,
        "police_called": True,
        "ems_called": True,
    },
    # Nowadays
    {
        "venue_id": "nowadays",
        "occurred_at": "2026-04-30T23:50:00",
        "location": "Outdoor Patio",
        "summary": "Patron vandalized two patio tables and a speaker enclosure before being removed by security. Estimated $800 in damage.",
        "reported_by": "Bar Manager",
        "injury_observed": False,
        "police_called": True,
        "ems_called": False,
    },
    {
        "venue_id": "nowadays",
        "occurred_at": "2026-04-12T21:00:00",
        "location": "Front Bar",
        "summary": "Staff served a visibly intoxicated patron who later fell in the parking lot. Patron declined EMS but filed a complaint the next day.",
        "reported_by": "Bartender",
        "injury_observed": True,
        "police_called": False,
        "ems_called": False,
    },
    # Market Hotel
    {
        "venue_id": "market-hotel",
        "occurred_at": "2026-05-03T21:20:00",
        "location": "Stage Left",
        "summary": "Electrical short caused a small fire behind the stage monitor stack. Staff evacuated venue and used fire extinguisher. No injuries.",
        "reported_by": "Production Manager",
        "injury_observed": False,
        "police_called": False,
        "ems_called": False,
    },
    {
        "venue_id": "market-hotel",
        "occurred_at": "2026-04-22T23:10:00",
        "location": "Main Bar",
        "summary": "Bouncer used excessive force when removing a patron who refused to leave. Patron claims injuries to shoulder. Police arrived post-incident.",
        "reported_by": "Venue Owner",
        "injury_observed": True,
        "police_called": True,
        "ems_called": True,
    },
]


KNOWLEDGE_SOURCES = [
    # Elsewhere Brooklyn — venue-specific
    {
        "source_id": "policy-2026-liquor-liability",
        "venue_id": "elsewhere-brooklyn",
        "source_type": "policy",
        "text": "Liquor liability policy requires documented security response and incident records for altercations.",
    },
    {
        "source_id": "staffing-2026-05-02",
        "venue_id": "elsewhere-brooklyn",
        "source_type": "staffing",
        "text": "Security shift log confirms 6 floor staff and 4 licensed security guards scheduled for the sold-out DJ event.",
    },
    {
        "source_id": "controls-questionnaire-2026",
        "venue_id": "elsewhere-brooklyn",
        "source_type": "questionnaire",
        "text": "Venue procedure requires staff to preserve clips, collect witness details, and complete incident reports before close.",
    },
    # Shared — apply to all venues (venue_id="*")
    {
        "source_id": "shared-policy-duty-of-care",
        "venue_id": "*",
        "source_type": "policy",
        "text": "Duty of care standard requires venues to take reasonable steps to prevent foreseeable harm to patrons. Security response must be documented within 30 seconds of detected aggression.",
    },
    {
        "source_id": "shared-policy-liquor-liability",
        "venue_id": "*",
        "source_type": "policy",
        "text": "Liquor liability coverage requires documented proof that staff completed responsible service training. Over-service of visibly intoxicated patrons voids claims defense.",
    },
    {
        "source_id": "shared-policy-premises-liability",
        "venue_id": "*",
        "source_type": "policy",
        "text": "Premises liability requires venues to maintain safe conditions including wet floor signage, adequate lighting on stairs, and regular hazard inspections.",
    },
    {
        "source_id": "shared-policy-dram-shop",
        "venue_id": "*",
        "source_type": "policy",
        "text": "Dram shop laws hold venues liable for damages caused by intoxicated patrons served alcohol after visible impairment. Service cutoff documentation is required for claims defense.",
    },
    {
        "source_id": "shared-policy-incident-reporting",
        "venue_id": "*",
        "source_type": "policy",
        "text": "All incidents must be reported within 24 hours of occurrence. Delayed reporting weakens claims defensibility and may void coverage for the specific incident.",
    },
    {
        "source_id": "shared-compliance-camera-retention",
        "venue_id": "*",
        "source_type": "compliance",
        "text": "Camera footage relevant to an incident must be preserved for a minimum of 90 days. Footage deletion prior to this window constitutes a compliance violation.",
    },
    {
        "source_id": "shared-compliance-security-staffing",
        "venue_id": "*",
        "source_type": "compliance",
        "text": "Venues with capacity over 300 must maintain a minimum ratio of 1 licensed security guard per 75 patrons during events. Staffing logs must be retained for 12 months.",
    },
    {
        "source_id": "shared-compliance-medical-response",
        "venue_id": "*",
        "source_type": "compliance",
        "text": "Medical emergencies require immediate EMS notification. Failure to call EMS for an unresponsive patron constitutes negligence and voids medical expense coverage.",
    },
]


STREAM_EVENTS = [
    {
        "source_id": "stream:door-count",
        "venue_id": "elsewhere-brooklyn",
        "at": "2026-05-02T23:12:00Z",
        "label": "Door count recorded 742 guests against 800 capacity.",
        "text": "Door count remained under stated capacity during the incident window.",
    },
    {
        "source_id": "stream:pos",
        "venue_id": "elsewhere-brooklyn",
        "at": "2026-05-02T23:10:00Z",
        "label": "POS aggregate shows normal transaction volume before the brawl.",
        "text": "POS activity did not show a sudden bar-service spike before the reported altercation.",
    },
    {
        "source_id": "stream:camera-rear-bar-clip",
        "venue_id": "elsewhere-brooklyn",
        "at": "2026-05-02T23:13:00Z",
        "label": "Camera metadata flagged a 90-second altercation-like motion event near rear bar.",
        "text": "Non-biometric camera metadata flagged a short altercation-like event near rear bar; human review is required.",
    },
]
